# Generated by ChatGPT - manual migration for division semester field
from django.db import migrations, models


def set_semester(apps, schema_editor):
    Division = apps.get_model('scheduler', 'Division')
    Semester = apps.get_model('scheduler', 'Semester')
    # assign current divisions to first semester of their course if available
    for div in Division.objects.all():
        if div.course_id and not div.semester_id:
            sem = Semester.objects.filter(course_id=div.course_id).order_by('number').first()
            if sem:
                div.semester_id = sem.id
                div.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='divisions', to='scheduler.semester'),
        ),
        migrations.RunPython(set_semester, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='division',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='course_divisions', to='scheduler.course'),
        ),
        # optionally enforce semester non-null after data migration?
        migrations.AlterField(
            model_name='division',
            name='semester',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='divisions', to='scheduler.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('name','semester')},
        ),
    ]
