# Generated by Django 6.0.2 on 2026-03-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_add_semester_to_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['semester__course', 'semester__number', 'name']},
        ),
        migrations.AlterField(
            model_name='division',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Semester this division belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='scheduler.semester'),
        ),
    ]
