# Generated by Django 6.0.2 on 2026-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_division_options_alter_division_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='break_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of breaks during the day'),
        ),
        migrations.AddField(
            model_name='semester',
            name='breaks',
            field=models.TextField(blank=True, help_text='Comma-separated break ranges (HH:MM-HH:MM)'),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Semester daily end time (e.g. 04:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Semester daily start time (e.g. 08:00 AM)', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='working_days',
            field=models.CharField(choices=[('MON-FRI', 'Monday–Friday'), ('MON-SAT', 'Monday–Saturday')], default='MON-FRI', help_text='Days of week when classes are held', max_length=7),
        ),
    ]
