# Generated by Django 6.0.2 on 2026-03-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_semester_break_count_semester_breaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='total_hours',
            field=models.PositiveSmallIntegerField(default=1, help_text='Total lecture hours for this subject during the semester'),
        ),
    ]
