# Generated by Django 6.0.2 on 2026-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_subject_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='max_lectures_per_day',
            field=models.PositiveSmallIntegerField(default=6, help_text='Maximum number of lecture slots allowed per day for this semester'),
        ),
    ]
