# Generated by Django 6.0.2 on 2026-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_semester_max_lectures_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='strength',
            field=models.PositiveIntegerField(default=0, help_text='Number of students in this division'),
        ),
    ]
