# Generated by Django 6.0.2 on 2026-03-04 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_division_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.division')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_assignments', to='scheduler.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_subjects', to='scheduler.teacher')),
            ],
            options={
                'ordering': ['division', 'subject'],
                'unique_together': {('division', 'subject')},
            },
        ),
    ]
