# Generated by Django 6.0.3 on 2026-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_teacher_subjects_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_known',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher is capable of teaching', related_name='qualified_teachers', to='scheduler.subject'),
        ),
    ]
