# Generated by Django 6.0.3 on 2026-03-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_ensure_teacher_subjects_known_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='known_subject_names',
            field=models.TextField(blank=True, default='', help_text='Reference-only subject names entered by user (comma separated).'),
        ),
    ]
