# Generated by Django 6.0.3 on 2026-03-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_teacher_known_subject_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division this timetable entry belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='scheduler.division'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('semester', 'division', 'day', 'time_slot', 'classroom')},
        ),
    ]
