# Generated by Django 6.0.3 on 2026-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_alter_timetable_unique_together_timetable_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='additional_departments',
            field=models.ManyToManyField(blank=True, help_text='Other departments this teacher can teach for', related_name='additional_teachers', to='scheduler.department'),
        ),
    ]
