# Generated by Django 6.0.3 on 2026-03-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division this room/lab is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='scheduler.division'),
        ),
    ]
