# Generated by Django 6.0.3 on 2026-03-18 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_classroom_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20)),
                ('from_roll_no', models.PositiveIntegerField()),
                ('to_roll_no', models.PositiveIntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_batch_assignments', to='scheduler.division')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_batch_assignments', to='scheduler.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_batch_assignments', to='scheduler.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_batch_assignments', to='scheduler.teacher')),
            ],
            options={
                'ordering': ['division', 'subject', 'batch_number'],
                'unique_together': {('division', 'subject', 'batch_number')},
            },
        ),
    ]
